version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=street-markets    
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./docker/postgres/DEINFO_AB_FEIRASLIVRES_2014.csv:/tmp/DEINFO_AB_FEIRASLIVRES_2014.csv
      - ./docker/postgres/import_csv.sql:/docker-entrypoint-initdb.d/import_csv.sql
    networks:
      - api-street-markets

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - api-street-markets

  street-markets-api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=street-markets
      - GIN_MODE=release
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - api-street-markets  
    command: /bin/sh -c 'while ! nc -z postgres 5432; do sleep 1; done; ./root/app;'
    restart: always 

networks:
  api-street-markets:
    driver: bridge      